### ISSUE TITLE
Use options from a file

### ISSUE THREAD

**Issue by rdumont** [vtex/releasy#5]
A file should be used to specify some defaults. In YAML, it could be something like:

``` yaml
# _releasy.yaml
default: prerelease        # the default release type
filename: mypackage.json   # the default version file
```

If the file doesn't exist, just don't use it. JSON could also be allowed.
